{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from os import listdir\n",
    "from os.path import isdir, join, exists\n",
    "import glob\n",
    "import subprocess\n",
    "import re\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "###############################################################################\n",
    "# REMatcher is a utility class to make regex's work similar to Perl\n",
    "# NOTE: if there are any changes needed in this function contact Sean.\n",
    "###############################################################################\n",
    "class REMatcher(object):\n",
    "    ''' This is a utility function to help out with matching regex's and\n",
    "        grabbing the matches out in a way that is similar to how perl\n",
    "        does it.\n",
    "    '''\n",
    "    def __init__(self, matchstring: str) -> None:\n",
    "        self.matchstring = matchstring\n",
    "\n",
    "    def match(self, regexp: str) -> bool:\n",
    "        self.rematch = re.match(regexp, self.matchstring,\n",
    "                                re.IGNORECASE |\n",
    "                                re.MULTILINE |\n",
    "                                re.DOTALL\n",
    "                                )\n",
    "        return bool(self.rematch)\n",
    "\n",
    "    def group(self, i: int) -> str:\n",
    "        return \"Error 999\" if self.rematch is None else self.rematch.group(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_make(dut: str, path_in: str, path_rpt: str):\n",
    "    my_command = 'make'\n",
    "    rpt = f'{dut}.txt'\n",
    "    output_file = f'{path_rpt}{rpt}'\n",
    "    py_file = f'{path_in}/__pycache__/'\n",
    "    if os.path.exists(py_file):\n",
    "        os.remove(py_file)\n",
    "\n",
    "    # Execute the command and capture both stdout and stderr\n",
    "    try:\n",
    "        completed_process = subprocess.run('make clean', shell=True, check=True, capture_output=True, text=True)\n",
    "        completed_process = subprocess.run(my_command, shell=True, check=True, capture_output=True, text=True)\n",
    "        output_text = completed_process.stdout\n",
    "\n",
    "        # Save the output to a file\n",
    "        with open(output_file, 'w') as file:\n",
    "            file.write(output_text)\n",
    "\n",
    "        # print(\"Command executed successfully. Output saved to:\", output_file)\n",
    "\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        print(\"Command failed with exit code:\", e.returncode)\n",
    "        print(\"Error message:\", e.stderr)\n",
    "        # Save the output to a file\n",
    "        with open(output_file, 'w') as file:\n",
    "            file.write(e.stderr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Command failed with exit code: 2\n",
      "Error message: make[1]: *** No rule to make target '/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/ksalu/../tinyalu_hdl/verilog/tinyalu.sv', needed by 'sim_build/sim.vvp'.  Stop.\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: make: *** No targets specified and no makefile found.  Stop.\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_dadda_tree_8/testbench.py\", line 46, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_dadda_tree_16/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_dadda_tree_32/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_8/testbench.py\", line 44, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_16/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_32/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_csa_8/testbench.py\", line 36, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_csa_16/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n",
      "Command failed with exit code: 2\n",
      "Error message: Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 233, in _initialise_testbench\n",
      "    _initialise_testbench_(argv_)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 316, in _initialise_testbench_\n",
      "    regression_manager = RegressionManager.from_discovery(top)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 174, in from_discovery\n",
      "    return cls(dut, tests)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 153, in __init__\n",
      "    for test in tests:\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 203, in _discover_tests\n",
      "    module = _my_import(module_name)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 72, in _my_import\n",
      "    mod = __import__(name)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 178, in exec_module\n",
      "    exec(co, module.__dict__)\n",
      "  File \"/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/math_multiplier_wallace_tree_csa_32/testbench.py\", line 37, in <module>\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/regression.py\", line 889, in generate_tests\n",
      "    'Adding generated test \"%s\" to module \"%s\"' % (name, mod.__name__)\n",
      "AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/__init__.py\", line 332, in _sim_event\n",
      "    scheduler.log.error(msg)\n",
      "AttributeError: 'NoneType' object has no attribute 'log'\n",
      "ERROR: results.xml was not written by the simulation!\n",
      "make[1]: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:96: results.xml] Error 1\n",
      "make: *** [/home/sean/github/RTL_Design_Projects/.venv/lib/python3.10/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2\n",
      "\n"
     ]
    }
   ],
   "source": [
    "path_in = '/home/sean/github/RTL_Design_Projects/val/common_cocotb_only/'\n",
    "path_rpt = '/home/sean/github/RTL_Design_Projects/reports/common_cocotb_only/'\n",
    "file_list = [f for f in listdir(path_in) if isdir(join(path_in, f))]\n",
    "current_dir = os.getcwd()\n",
    "\n",
    "for dut in sorted(file_list):\n",
    "    # print(f'Working on {dut}')\n",
    "    os.chdir(f'{path_in}{dut}')\n",
    "    run_make(dut, path_in, path_rpt)\n",
    "\n",
    "os.chdir(current_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
